version: '3'
services: 
    json_serve:
        build: ./serve_json
        volumes: 
            - /home/saify2j/Desktop/node-projects/little_todo_app/serve_json:/usr/src/app
        ports: 
            - 6002:8080

    todo_app:
        build: ./todo_app
        volumes: 
            - ./todo_app:/usr/src/app
        ports: 
            - 6001:8080
        depends_on: 
            - json_serve
